### ISSUE TITLE
Version 17.0.0 from FDroid fails to load on Android 13

### ISSUE THREAD

**Issue by BradNut** [lucasnlm/antimine-android#400]
**Describe the bug**
After installing the update to 17.0.0 from FDroid I cannot open the app. The app will crash immediately after showing the splash screen. The OS then asks the usual unexpected behavior questions such as App Info, Close App, Show Details.

**To Reproduce**
Install version 17.0.0 on Android 13?

**Expected behavior**
App should load

**Android Version:**
Pixel 7 Pro Graphene OS Android 13

**App Version**
17.0.0 installed from FDroid

```
type: crash
osVersion: google/cheetah/cheetah:13/TQ1A.230105.002/2023011000:user/release-keys
package: dev.lucanlm.antimine:1700001
process: dev.lucanlm.antimine
processUptime: 62 + 251 ms

java.lang.RuntimeException: Unable to create application dev.lucasnlm.antimine.MainApplication: l1.q: Couldn't load shared library 'gdx' for target: Android
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: l1.q: Couldn't load shared library 'gdx' for target: Android
	at l1.r.e(Unknown Source:113)
	at l1.e.a(Unknown Source:22)
	at dev.lucasnlm.antimine.MainApplication.onCreate(Unknown Source:6)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1282)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6765)
	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgdx.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at l1.r.e(Unknown Source:24)
	... 15 more
```

**Comment by BradNut** [comment]
Additional information: The previous version 16.1.1 from FDroid works correctly.

**Comment by Micha-Btz** [comment]
Same behavior on my pixel 5, Los 20 Android 13

**Comment by zimbipw** [comment]
Same on Volla Phone with VollaOS 11.1-20230111 (Android 11)

**Comment by DanielVALAT** [comment]
Same on Pixel 4a 5G (Android 13)

**Comment by bra1ncramp** [comment]
Same on Android 11
OnePlus 6T

**Comment by jlariviere1** [comment]
I experience the same bug on my P4a Graphene OS also

**Comment by DananaBanana** [comment]
Extra info that might be useful, I tried out the version on the Play Store and it works perfectly.

**Comment by Nighted** [comment]
1.7.0.0 crashes on start. Pixel 3a Android 11.

ALSO....please add an option to export the settings....I've had poke around a couple times now trying to get everything back just the way I had it before.

Thanks

P.S. I have donated before. ;)

**Comment by paulle** [comment]
Same here.
Sony Xperia 5 III
Android 13

**Comment by BloodRaven0** [comment]
Same on Poco X3 NFC, android 10

**Comment by lucasnlm** [comment]
Thanks for let me know about it!
I looks like F-droid server is failing to get libgdx .so files.

I'm working on a fix.

**Comment by lucasnlm** [comment]
> 1.7.0.0 crashes on start. 1.6.1.1 launches without issue. Pixel 3a: Android 11/CalyxOS.
> 
> Also....PLEASE add an option to export the settings....I've had poke around a couple times now trying to get everything back just the way I had it before. Very annoying. rage
> 
> Thanks
> 
> P.S. I have donated before. ;)

I will add that feature. :)

**Comment by lucasnlm** [comment]
> Extra info that might be useful, I tried out the version on the Play Store and it works perfectly.

The Play Store version is not updated yet. It still uses 16.1.1 version.
So, it's probably something with 17.0.0 only.

**Comment by lucasnlm** [comment]
I hope #401 fixes the problem.

**Comment by BradNut** [comment]
@lucasnlm Thank you! I will check once FDroid builds and deploys eventually.

**Comment by Nighted** [comment]
> I will add that feature. :)

Thank you, now I can take off my helmet. :)

**Comment by lucasnlm** [comment]
@Nighted Like promised, the export / import button will be available on the bottom of Settings screens:

<img src="https://user-images.githubusercontent.com/1326126/213897838-97d64038-b897-478d-bd42-976644f83145.png" width="250px" />

I hope to get it available next week.

**Comment by Tanmandal** [comment]
java.lang.RuntimeException: Unable to create application dev.lucasnlm.antimine.MainApplication: l1.q: Couldn't load shared library 'gdx' for target: Android
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7109)
	at android.app.ActivityThread.access$1600(ActivityThread.java:271)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: l1.q: Couldn't load shared library 'gdx' for target: Android
	at l1.r.e(Unknown Source:113)
	at l1.e.a(Unknown Source:22)
	at dev.lucasnlm.antimine.MainApplication.onCreate(Unknown Source:6)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1212)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7103)
	... 9 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgdx.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at l1.r.e(Unknown Source:24)
	... 13 more

**Comment by BradNut** [comment]
@lucasnlm Working fine now on version 17.0.1. Thank you!
