### ISSUE TITLE
crashes when trying to access the application

### ISSUE THREAD

**Issue by Wjxfi** [lucasnlm/antimine-android#403]
**Android Version:**
12 miui 12.0.5

**App Version**
Fdroid latest

FATAL EXCEPTION: main
Process: dev.lucanlm.antimine, PID: 8930
java.lang.RuntimeException: Unable to create application dev.lucasnlm.antimine.MainApplication: l1.q: Couldn't load shared library 'gdx' for target: Android
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7079)
	at android.app.ActivityThread.access$1600(ActivityThread.java:276)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2130)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: l1.q: Couldn't load shared library 'gdx' for target: Android
	at l1.r.e(Unknown Source:113)
	at l1.e.a(Unknown Source:22)
	at dev.lucasnlm.antimine.MainApplication.onCreate(Unknown Source:6)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7073)
	... 9 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgdx.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at l1.r.e(Unknown Source:24)
	... 13 more

**Comment by lucasnlm** [comment]
It's the same crash of #400. It was already fixed and will be available on F-droid as soon it build the new version, 17.0.1.
