### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by ceeray** [lucasnlm/antimine-android#411]
The new version crashes for me upon start, after reboot and after clearing cache. F droid won't even let me downgrade without uninstalling first 😔 on a Samsung A-71 / Android 13

**Comment by krayon** [comment]
Since no one else has posted a me too, I will, but would encourage later reporters to just click the thumbs up to register your "me too"  :-P

**Comment by lucasnlm** [comment]
I looks like it happens only on F-droid again. I will investigate.

<img src="https://user-images.githubusercontent.com/1326126/221250361-4e297e4a-45e6-4f8c-8ba6-0e400155bebf.png" width="200px"/>

**Comment by Timofei302** [comment]
The game crashes when trying to launch
Samsung Galaxy A30s (with Magisk)
Latest version from F-Droid
![Screenshot_20230225-104026_One UI Home.translated.jpg](https://user-images.githubusercontent.com/59145732/221345333-bb3fbd26-52ea-4444-9154-b783fe48b256.jpg)

**Comment by askorbinovaya-kislota** [comment]
<details>
<summary>stacktrace</summary>

```java
java.lang.ExceptionInInitializerError
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at androidx.core.app.CoreComponentFactory.instantiateApplication(Unknown Source:0)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1177)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1369)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7053)
	at android.app.ActivityThread.access$1600(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: com.badlogic.gdx.utils.SharedLibraryLoadRuntimeException: Couldn't load shared library 'gdx' for target: Android
	at h1.p.e(Unknown Source:113)
	at h1.e.a(Unknown Source:22)
	at dev.lucasnlm.antimine.MainApplication.<clinit>(Unknown Source:8)
	... 15 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgdx.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at h1.p.e(Unknown Source:24)
	... 17 more
```
</details>

**Comment by lucasnlm** [comment]
It looks like it works on 17.0.1 but crashes on the new version. Again it's failing to load the libgdx library because F-droid can't get then on build time for some reason. I will investigate more.

**Comment by j12i** [comment]
Good to know you're working on it, thanks a lot!
I also get Antimine from F-Droid, 17.0.0 crashed on startup, 17.0.1 worked, 17.1.5 crashing again. Note this is on Android 5.

**Comment by j12i** [comment]
just going to leave this here for convenience: [f-droid build log of 17.1.5](https://f-droid.org/repo/dev.lucanlm.antimine_1701051.log.gz)

**Comment by xmha97** [comment]
https://user-images.githubusercontent.com/23485114/221551755-c07a1003-0030-437b-835b-57167316a869.mp4

# Log
```
java.lang.ExceptionInInitializerError
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at androidx.core.app.CoreComponentFactory.instantiateApplication(Unknown Source:0)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1243)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1493)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1426)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6962)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2228)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8143)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: com.badlogic.gdx.utils.SharedLibraryLoadRuntimeException: Couldn't load shared library 'gdx' for target: Android
	at h1.p.e(Unknown Source:113)
	at h1.e.a(Unknown Source:22)
	at dev.lucasnlm.antimine.MainApplication.<clinit>(Unknown Source:8)
	... 16 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgdx.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at h1.p.e(Unknown Source:24)
	... 18 more
```

**Comment by Timofei302** [comment]
LogCat from Samsung Galaxy A30s (with Magisk)
```
FATAL EXCEPTION: main
Process: dev.lucanlm.antimine, PID: 31280
java.lang.ExceptionInInitializerError
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at androidx.core.app.CoreComponentFactory.instantiateApplication(Unknown Source:0)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1324)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7543)
	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: com.badlogic.gdx.utils.SharedLibraryLoadRuntimeException: Couldn't load shared library 'gdx' for target: Android
	at h1.p.e(Unknown Source:113)
	at h1.e.a(Unknown Source:22)
	at dev.lucasnlm.antimine.MainApplication.<clinit>(Unknown Source:8)
	... 14 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgdx.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
	at java.lang.System.loadLibrary(System.java:1664)
	at h1.p.e(Unknown Source:24)
	... 16 more
```

**Comment by lucasnlm** [comment]
I just released a new version that fixes this problem (I hope).
Since I don't know how long it will take to be available on F-droid, I'm adding the apk on the releases page too. [Here](https://github.com/lucasnlm/antimine-android/releases/tag/17.1.7).

Sorry for this problem again! I hope to add a test or something to avoid it in the future.

**Comment by j12i** [comment]
Hi! The new Version (17.1.7 F) just appeared in F-Droid for me.

**Comment by sambonbonne** [comment]
I can confirm the new version works fine for me too!
