### ISSUE TITLE
[17.2.0 F] Instant crash on Android 5.1.1

### ISSUE THREAD

**Issue by j12i** [lucasnlm/antimine-android#422]
**Describe the bug**
when starting the app, I get only a dialog box that it has crashed, every time

**To Reproduce**
start antimine

**Expected behavior**
app opens

**Android Version:**
5.1.1

**App Version**
17.2.0 F

```log
I/ActivityManager(  870): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=dev.lucanlm.antimine cmp=dev.lucanlm.antimine/dev.lucasnlm.antimine.main.MainActivity} from uid 10246 on display 0
V/WindowManager(  870): addAppToken: AppWindowToken{2f7752fc token=Token{3fd4b7ef ActivityRecord{df39cce u0 dev.lucanlm.antimine/dev.lucasnlm.antimine.main.MainActivity t2026}}} to stack=1 task=2026 at 0
V/WindowManager(  870): Adding window Window{2fbe6832 u0 Starting dev.lucanlm.antimine} at 13 of 19 (after Window{2fd287bb u0 org.fdroid.fdroid/org.fdroid.fdroid.views.AppDetailsActivity})
I/ActivityManager(  870): Start proc 11652:dev.lucanlm.antimine/u0a319 for activity dev.lucanlm.antimine/dev.lucasnlm.antimine.main.MainActivity
...
E/AndroidRuntime(11652): FATAL EXCEPTION: main
E/AndroidRuntime(11652): Process: dev.lucanlm.antimine, PID: 11652
E/AndroidRuntime(11652): java.lang.ExceptionInInitializerError
E/AndroidRuntime(11652):        at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime(11652):        at java.lang.Class.newInstance(Class.java:1606)
E/AndroidRuntime(11652):        at android.app.Instrumentation.newApplication(Instrumentation.java:995)
E/AndroidRuntime(11652):        at android.app.Instrumentation.newApplication(Instrumentation.java:980)
E/AndroidRuntime(11652):        at android.app.LoadedApk.makeApplication(LoadedApk.java:564)
E/AndroidRuntime(11652):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4634)
E/AndroidRuntime(11652):        at android.app.ActivityThread.access$1500(ActivityThread.java:156)
E/AndroidRuntime(11652):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
E/AndroidRuntime(11652):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11652):        at android.os.Looper.loop(Looper.java:211)
E/AndroidRuntime(11652):        at android.app.ActivityThread.main(ActivityThread.java:5389)
E/AndroidRuntime(11652):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11652):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(11652):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
E/AndroidRuntime(11652):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
E/AndroidRuntime(11652): Caused by: com.badlogic.gdx.utils.SharedLibraryLoadRuntimeException: Couldn't load shared library 'gdx' for target: Android
E/AndroidRuntime(11652):        at i1.p.e(SourceFile)
E/AndroidRuntime(11652):        at i1.e.a(SourceFile)
E/AndroidRuntime(11652):        at dev.lucasnlm.antimine.MainApplication.<clinit>(SourceFile)
E/AndroidRuntime(11652):        ... 15 more
E/AndroidRuntime(11652): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/dev.lucanlm.antimine-1/base.apk"],nativeLibraryDirectories=[/data/app/dev.lucanlm.antimine-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgdx.so"
E/AndroidRuntime(11652):        at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime(11652):        at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime(11652):        ... 18 more
...
D/ActivityManager(  870): New dropbox entry: dev.lucanlm.antimine, data_app_crash, 46fe69a8-1339-4e2a-a2d6-652164641bd6
W/ActivityManager(  870):   Force finishing activity 1 dev.lucanlm.antimine/dev.lucasnlm.antimine.main.MainActivity
...
W/ActivityManager(  870): Activity pause timeout for ActivityRecord{df39cce u0 dev.lucanlm.antimine/dev.lucasnlm.antimine.main.MainActivity t2026 f}
...
I/ActivityManager(  870): Process dev.lucanlm.antimine (pid 11652) has died
```

Maybe the solution is found [here](https://github.com/libgdx/libgdx/issues/5863#issuecomment-1119074096)?

**Comment by lucasnlm** [comment]
Again the same libgdx missing .so issue. :(
I just sent a new release, I hope F-droid update soon.

**Comment by Quantenzitrone** [comment]
i just went here to report the bug after updating
happy to see it has already been fixed 💚

**Comment by j12i** [comment]
Does that mean really f-droid should be doing what I linked to?

**Comment by vp800** [comment]
Where can I download the apk of low versions? The lowest F-Droid version is 17.1.5
I'm looking for 17.0.1 or 17.0.0

**Comment by EVOTk** [comment]
Same issue for me
Version 17.2.0F on F-droid
Honor 70 android 12

Instant crash on launch

**Comment by lucasnlm** [comment]
@vp800 You can download it here https://github.com/lucasnlm/antimine-android/releases/tag/17.1.7

**Comment by lucasnlm** [comment]
This crash is due to missing libgdx .so files.
#427 adds a Github Workflow check to ensure this problem won't happens again.

**Comment by lucasnlm** [comment]
The newest version (with the crash fix) is available here: https://github.com/lucasnlm/antimine-android/releases/tag/17.2.2

**Comment by EVOTk** [comment]
Work for me, thx

**Comment by bbaster** [comment]
Does 17.2.1F work?

**Comment by j12i** [comment]
17.2.1 F came up on on f-droid sunday afternoon (UTC) and doesn't crash for me. Thanks Lucas!
